import type { CategoryDef } from '../types/word';

export const categories: Record<string, CategoryDef> = {
  hayvanlar: {
    name: 'Hayvanlar',
    emoji: '🐾',
    words: [
      { word: 'kedi', difficulty: 1 },
      { word: 'köpek', difficulty: 1 },
      { word: 'kuş', difficulty: 1 },
      { word: 'balık', difficulty: 1 },
      { word: 'tavuk', difficulty: 1 },
      { word: 'inek', difficulty: 1 },
      { word: 'at', difficulty: 1 },
      { word: 'fare', difficulty: 1 },
      { word: 'kurbağa', difficulty: 1 },
      { word: 'arı', difficulty: 1 },
      { word: 'aslan', difficulty: 1 },
      { word: 'kaplan', difficulty: 1 },
      { word: 'fil', difficulty: 1 },
      { word: 'maymun', difficulty: 1 },
      { word: 'tavşan', difficulty: 1 },
      { word: 'ayı', difficulty: 1 },
      { word: 'koyun', difficulty: 1 },
      { word: 'keçi', difficulty: 1 },
      { word: 'eşek', difficulty: 1 },
      { word: 'domuz', difficulty: 1 },
      { word: 'ördek', difficulty: 1 },
      { word: 'kaz', difficulty: 1 },
      { word: 'güvercin', difficulty: 1 },
      { word: 'yılan', difficulty: 2 },
      { word: 'penguen', difficulty: 2 },
      { word: 'kaplumbağa', difficulty: 2 },
      { word: 'timsah', difficulty: 2 },
      { word: 'flamingo', difficulty: 2 },
      { word: 'ahtapot', difficulty: 2 },
      { word: 'papağan', difficulty: 2 },
      { word: 'kartal', difficulty: 2 },
      { word: 'yunus', difficulty: 2 },
      { word: 'balina', difficulty: 2 },
      { word: 'zürafa', difficulty: 2 },
      { word: 'gergedan', difficulty: 2 },
      { word: 'su aygırı', difficulty: 2 },
      { word: 'koala', difficulty: 2 },
      { word: 'kanguru', difficulty: 2 },
      { word: 'kirpi', difficulty: 2 },
      { word: 'sincap', difficulty: 2 },
      { word: 'baykuş', difficulty: 2 },
      { word: 'panda', difficulty: 2 },
      { word: 'hamsi', difficulty: 2 },
      { word: 'karınca', difficulty: 2 },
      { word: 'örümcek', difficulty: 2 },
      { word: 'deve', difficulty: 2 },
      { word: 'kurt', difficulty: 2 },
      { word: 'tilki', difficulty: 2 },
      { word: 'leopar', difficulty: 2 },
      { word: 'çita', difficulty: 2 },
      { word: 'pelikan', difficulty: 2 },
      { word: 'leylek', difficulty: 2 },
      { word: 'solucan', difficulty: 2 },
      { word: 'salyangoz', difficulty: 2 },
      { word: 'kelebek', difficulty: 2 },
      { word: 'uğur böceği', difficulty: 2 },
      { word: 'köpek balığı', difficulty: 2 },
      { word: 'yengeç', difficulty: 2 },
      { word: 'istakoz', difficulty: 2 },
      { word: 'bukalemun', difficulty: 3 },
      { word: 'kunduz', difficulty: 3 },
      { word: 'iguana', difficulty: 3 },
      { word: 'denizanası', difficulty: 3 },
      { word: 'yarasa', difficulty: 3 },
      { word: 'susamuru', difficulty: 3 },
      { word: 'kelaynak', difficulty: 3 },
      { word: 'okapi', difficulty: 3 },
      { word: 'kamelya', difficulty: 3 },
      { word: 'deniz atı', difficulty: 2 },
      { word: 'denizyıldızı', difficulty: 2 },
    ],
  },
  yiyecekler: {
    name: 'Yiyecek & İçecek',
    emoji: '🍕',
    words: [
      { word: 'pizza', difficulty: 1 },
      { word: 'hamburger', difficulty: 1 },
      { word: 'simit', difficulty: 1 },
      { word: 'ekmek', difficulty: 1 },
      { word: 'peynir', difficulty: 1 },
      { word: 'yumurta', difficulty: 1 },
      { word: 'elma', difficulty: 1 },
      { word: 'muz', difficulty: 1 },
      { word: 'çikolata', difficulty: 1 },
      { word: 'dondurma', difficulty: 1 },
      { word: 'pasta', difficulty: 1 },
      { word: 'çay', difficulty: 1 },
      { word: 'kahve', difficulty: 1 },
      { word: 'süt', difficulty: 1 },
      { word: 'su', difficulty: 1 },
      { word: 'pide', difficulty: 1 },
      { word: 'döner', difficulty: 1 },
      { word: 'köfte', difficulty: 1 },
      { word: 'pilav', difficulty: 1 },
      { word: 'çorba', difficulty: 1 },
      { word: 'salata', difficulty: 1 },
      { word: 'makarna', difficulty: 1 },
      { word: 'sandviç', difficulty: 1 },
      { word: 'popcorn', difficulty: 1 },
      { word: 'karpuz', difficulty: 1 },
      { word: 'çilek', difficulty: 1 },
      { word: 'portakal', difficulty: 1 },
      { word: 'limon', difficulty: 1 },
      { word: 'üzüm', difficulty: 1 },
      { word: 'kiraz', difficulty: 1 },
      { word: 'domates', difficulty: 1 },
      { word: 'biber', difficulty: 1 },
      { word: 'soğan', difficulty: 1 },
      { word: 'bal', difficulty: 1 },
      { word: 'baklava', difficulty: 2 },
      { word: 'iskender', difficulty: 2 },
      { word: 'mantı', difficulty: 2 },
      { word: 'künefe', difficulty: 2 },
      { word: 'lahmacun', difficulty: 2 },
      { word: 'patates kızartması', difficulty: 2 },
      { word: 'sushi', difficulty: 2 },
      { word: 'krep', difficulty: 2 },
      { word: 'waffle', difficulty: 2 },
      { word: 'sarımsak', difficulty: 2 },
      { word: 'zeytin', difficulty: 2 },
      { word: 'reçel', difficulty: 2 },
      { word: 'turşu', difficulty: 2 },
      { word: 'lokum', difficulty: 2 },
      { word: 'börek', difficulty: 1 },
      { word: 'gözleme', difficulty: 2 },
      { word: 'ayran', difficulty: 1 },
      { word: 'şalgam', difficulty: 2 },
      { word: 'kavun', difficulty: 1 },
      { word: 'şeftali', difficulty: 1 },
      { word: 'armut', difficulty: 1 },
      { word: 'erik', difficulty: 1 },
      { word: 'kayısı', difficulty: 2 },
      { word: 'nar', difficulty: 1 },
      { word: 'incir', difficulty: 2 },
      { word: 'hurma', difficulty: 2 },
      { word: 'ceviz', difficulty: 2 },
      { word: 'fındık', difficulty: 2 },
      { word: 'badem', difficulty: 2 },
      { word: 'çiğ köfte', difficulty: 3 },
      { word: 'midye dolma', difficulty: 3 },
      { word: 'aşure', difficulty: 3 },
      { word: 'hünkâr beğendi', difficulty: 3 },
      { word: 'karnıyarık', difficulty: 3 },
      { word: 'imam bayıldı', difficulty: 3 },
      { word: 'su böreği', difficulty: 2 },
      { word: 'mercimek çorbası', difficulty: 2 },
    ],
  },
  sporlar: {
    name: 'Sporlar',
    emoji: '⚽',
    words: [
      { word: 'futbol', difficulty: 1 },
      { word: 'basketbol', difficulty: 1 },
      { word: 'voleybol', difficulty: 1 },
      { word: 'tenis', difficulty: 1 },
      { word: 'yüzme', difficulty: 1 },
      { word: 'koşu', difficulty: 1 },
      { word: 'bisiklet', difficulty: 1 },
      { word: 'kayak', difficulty: 1 },
      { word: 'boks', difficulty: 1 },
      { word: 'golf', difficulty: 1 },
      { word: 'bowling', difficulty: 1 },
      { word: 'güreş', difficulty: 2 },
      { word: 'okçuluk', difficulty: 2 },
      { word: 'beyzbol', difficulty: 2 },
      { word: 'rugby', difficulty: 2 },
      { word: 'sörf', difficulty: 2 },
      { word: 'dalış', difficulty: 2 },
      { word: 'yelken', difficulty: 2 },
      { word: 'jimnastik', difficulty: 2 },
      { word: 'atletizm', difficulty: 2 },
      { word: 'masa tenisi', difficulty: 2 },
      { word: 'badminton', difficulty: 2 },
      { word: 'hokey', difficulty: 2 },
      { word: 'karate', difficulty: 2 },
      { word: 'judo', difficulty: 2 },
      { word: 'halter', difficulty: 2 },
      { word: 'buz pateni', difficulty: 2 },
      { word: 'snowboard', difficulty: 2 },
      { word: 'dart', difficulty: 2 },
      { word: 'kürek', difficulty: 2 },
      { word: 'kano', difficulty: 2 },
      { word: 'rafting', difficulty: 2 },
      { word: 'paraşüt', difficulty: 2 },
      { word: 'tırmanma', difficulty: 2 },
      { word: 'hentbol', difficulty: 2 },
      { word: 'kriket', difficulty: 2 },
      { word: 'bilardo', difficulty: 2 },
      { word: 'binicilik', difficulty: 2 },
      { word: 'tekvando', difficulty: 2 },
      { word: 'triatlon', difficulty: 3 },
      { word: 'su topu', difficulty: 2 },
      { word: 'buz hokeyi', difficulty: 2 },
      { word: 'yamaç paraşütü', difficulty: 3 },
      { word: 'dağ bisikleti', difficulty: 2 },
      { word: 'salon futbolu', difficulty: 2 },
      { word: 'kickboks', difficulty: 2 },
      { word: 'sumo', difficulty: 2 },
      { word: 'wushu', difficulty: 3 },
      { word: 'eskrim', difficulty: 3 },
      { word: 'curling', difficulty: 3 },
      { word: 'polo', difficulty: 2 },
      { word: 'ralli', difficulty: 2 },
      { word: 'motokros', difficulty: 2 },
      { word: 'jimnastik halkası', difficulty: 3 },
      { word: 'cirit atma', difficulty: 2 },
      { word: 'disk atma', difficulty: 2 },
      { word: 'uzun atlama', difficulty: 2 },
      { word: 'yüksek atlama', difficulty: 2 },
      { word: 'sırıkla atlama', difficulty: 3 },
      { word: 'maraton', difficulty: 2 },
    ],
  },
  meslekler: {
    name: 'Meslekler',
    emoji: '👨‍🔬',
    words: [
      { word: 'doktor', difficulty: 1 },
      { word: 'öğretmen', difficulty: 1 },
      { word: 'polis', difficulty: 1 },
      { word: 'itfaiyeci', difficulty: 1 },
      { word: 'aşçı', difficulty: 1 },
      { word: 'pilot', difficulty: 1 },
      { word: 'hemşire', difficulty: 1 },
      { word: 'çiftçi', difficulty: 1 },
      { word: 'garson', difficulty: 1 },
      { word: 'berber', difficulty: 1 },
      { word: 'astronot', difficulty: 2 },
      { word: 'mühendis', difficulty: 2 },
      { word: 'avukat', difficulty: 2 },
      { word: 'kasap', difficulty: 2 },
      { word: 'fırıncı', difficulty: 2 },
      { word: 'kaptan', difficulty: 2 },
      { word: 'dalgıç', difficulty: 2 },
      { word: 'ressam', difficulty: 2 },
      { word: 'müzisyen', difficulty: 2 },
      { word: 'aktör', difficulty: 2 },
      { word: 'yönetmen', difficulty: 2 },
      { word: 'gazeteci', difficulty: 2 },
      { word: 'fotoğrafçı', difficulty: 2 },
      { word: 'mimar', difficulty: 2 },
      { word: 'diş hekimi', difficulty: 2 },
      { word: 'eczacı', difficulty: 2 },
      { word: 'veteriner', difficulty: 2 },
      { word: 'programcı', difficulty: 2 },
      { word: 'terzi', difficulty: 2 },
      { word: 'marangoz', difficulty: 2 },
      { word: 'tesisatçı', difficulty: 2 },
      { word: 'elektrikçi', difficulty: 2 },
      { word: 'boyacı', difficulty: 2 },
      { word: 'bahçıvan', difficulty: 2 },
      { word: 'balıkçı', difficulty: 1 },
      { word: 'postacı', difficulty: 1 },
      { word: 'şoför', difficulty: 1 },
      { word: 'kapıcı', difficulty: 1 },
      { word: 'hakem', difficulty: 2 },
      { word: 'antrenör', difficulty: 2 },
      { word: 'psikolog', difficulty: 2 },
      { word: 'hâkim', difficulty: 2 },
      { word: 'savcı', difficulty: 2 },
      { word: 'diplomat', difficulty: 3 },
      { word: 'arkeolog', difficulty: 3 },
      { word: 'cerrah', difficulty: 3 },
      { word: 'jeolog', difficulty: 3 },
      { word: 'biyolog', difficulty: 3 },
      { word: 'kimyager', difficulty: 3 },
      { word: 'fizikçi', difficulty: 3 },
      { word: 'noter', difficulty: 3 },
      { word: 'kütüphaneci', difficulty: 2 },
      { word: 'müfettiş', difficulty: 3 },
      { word: 'savaş muhabiri', difficulty: 3 },
      { word: 'sunucu', difficulty: 2 },
      { word: 'komedyen', difficulty: 2 },
      { word: 'dansçı', difficulty: 2 },
      { word: 'heykeltıraş', difficulty: 3 },
      { word: 'kameraman', difficulty: 2 },
      { word: 'kuvaför', difficulty: 2 },
    ],
  },
  nesneler: {
    name: 'Günlük Nesneler',
    emoji: '🪑',
    words: [
      { word: 'telefon', difficulty: 1 },
      { word: 'bilgisayar', difficulty: 1 },
      { word: 'televizyon', difficulty: 1 },
      { word: 'saat', difficulty: 1 },
      { word: 'gözlük', difficulty: 1 },
      { word: 'şemsiye', difficulty: 1 },
      { word: 'anahtar', difficulty: 1 },
      { word: 'çanta', difficulty: 1 },
      { word: 'ayakkabı', difficulty: 1 },
      { word: 'şapka', difficulty: 1 },
      { word: 'kalem', difficulty: 1 },
      { word: 'kitap', difficulty: 1 },
      { word: 'masa', difficulty: 1 },
      { word: 'sandalye', difficulty: 1 },
      { word: 'yatak', difficulty: 1 },
      { word: 'ampul', difficulty: 1 },
      { word: 'mum', difficulty: 1 },
      { word: 'ayna', difficulty: 1 },
      { word: 'tarak', difficulty: 1 },
      { word: 'sabun', difficulty: 1 },
      { word: 'havlu', difficulty: 1 },
      { word: 'bardak', difficulty: 1 },
      { word: 'tabak', difficulty: 1 },
      { word: 'çatal', difficulty: 1 },
      { word: 'bıçak', difficulty: 1 },
      { word: 'kaşık', difficulty: 1 },
      { word: 'tencere', difficulty: 1 },
      { word: 'makas', difficulty: 1 },
      { word: 'halı', difficulty: 1 },
      { word: 'yastık', difficulty: 1 },
      { word: 'kulaklık', difficulty: 1 },
      { word: 'buzdolabı', difficulty: 2 },
      { word: 'çamaşır makinesi', difficulty: 2 },
      { word: 'elektrik süpürgesi', difficulty: 2 },
      { word: 'iğne', difficulty: 2 },
      { word: 'düğme', difficulty: 2 },
      { word: 'perde', difficulty: 2 },
      { word: 'battaniye', difficulty: 2 },
      { word: 'priz', difficulty: 2 },
      { word: 'çakmak', difficulty: 2 },
      { word: 'cüzdan', difficulty: 1 },
      { word: 'anahtarlık', difficulty: 2 },
      { word: 'termos', difficulty: 2 },
      { word: 'fener', difficulty: 1 },
      { word: 'ip', difficulty: 1 },
      { word: 'çekiç', difficulty: 1 },
      { word: 'tornavida', difficulty: 2 },
      { word: 'pense', difficulty: 2 },
      { word: 'testere', difficulty: 2 },
      { word: 'süpürge', difficulty: 1 },
      { word: 'kova', difficulty: 1 },
      { word: 'sepet', difficulty: 1 },
      { word: 'valiz', difficulty: 2 },
      { word: 'dolap', difficulty: 1 },
      { word: 'raf', difficulty: 1 },
      { word: 'çerçeve', difficulty: 2 },
      { word: 'vazo', difficulty: 1 },
      { word: 'saksı', difficulty: 2 },
      { word: 'kibrit', difficulty: 2 },
      { word: 'ütü', difficulty: 1 },
      { word: 'askı', difficulty: 2 },
      { word: 'fermuar', difficulty: 2 },
      { word: 'cetvel', difficulty: 2 },
      { word: 'silgi', difficulty: 1 },
      { word: 'defter', difficulty: 1 },
      { word: 'zarf', difficulty: 2 },
      { word: 'pul', difficulty: 2 },
      { word: 'bant', difficulty: 2 },
    ],
  },
  doga: {
    name: 'Doğa',
    emoji: '🌿',
    words: [
      { word: 'güneş', difficulty: 1 },
      { word: 'ay', difficulty: 1 },
      { word: 'yıldız', difficulty: 1 },
      { word: 'bulut', difficulty: 1 },
      { word: 'yağmur', difficulty: 1 },
      { word: 'kar', difficulty: 1 },
      { word: 'ağaç', difficulty: 1 },
      { word: 'çiçek', difficulty: 1 },
      { word: 'dağ', difficulty: 1 },
      { word: 'deniz', difficulty: 1 },
      { word: 'göl', difficulty: 1 },
      { word: 'nehir', difficulty: 1 },
      { word: 'orman', difficulty: 1 },
      { word: 'ada', difficulty: 1 },
      { word: 'gökkuşağı', difficulty: 2 },
      { word: 'şelale', difficulty: 2 },
      { word: 'volkan', difficulty: 2 },
      { word: 'deprem', difficulty: 2 },
      { word: 'çöl', difficulty: 2 },
      { word: 'okyanus', difficulty: 2 },
      { word: 'mağara', difficulty: 2 },
      { word: 'yanardağ', difficulty: 2 },
      { word: 'fırtına', difficulty: 2 },
      { word: 'gün batımı', difficulty: 2 },
      { word: 'gün doğumu', difficulty: 2 },
      { word: 'çimen', difficulty: 1 },
      { word: 'yaprak', difficulty: 1 },
      { word: 'dal', difficulty: 1 },
      { word: 'kök', difficulty: 2 },
      { word: 'tohum', difficulty: 2 },
      { word: 'toprak', difficulty: 1 },
      { word: 'kum', difficulty: 1 },
      { word: 'taş', difficulty: 1 },
      { word: 'kaya', difficulty: 1 },
      { word: 'dere', difficulty: 1 },
      { word: 'çağlayan', difficulty: 2 },
      { word: 'vadi', difficulty: 2 },
      { word: 'ova', difficulty: 2 },
      { word: 'tepe', difficulty: 1 },
      { word: 'uçurum', difficulty: 2 },
      { word: 'kaynak', difficulty: 2 },
      { word: 'bataklık', difficulty: 2 },
      { word: 'bozkır', difficulty: 2 },
      { word: 'çayır', difficulty: 2 },
      { word: 'palmiye', difficulty: 2 },
      { word: 'kaktüs', difficulty: 2 },
      { word: 'mantar', difficulty: 1 },
      { word: 'yosun', difficulty: 2 },
      { word: 'gül', difficulty: 1 },
      { word: 'papatya', difficulty: 1 },
      { word: 'lale', difficulty: 1 },
      { word: 'orkide', difficulty: 2 },
      { word: 'ayçiçeği', difficulty: 2 },
      { word: 'dolu', difficulty: 2 },
      { word: 'sis', difficulty: 1 },
      { word: 'rüzgâr', difficulty: 2 },
      { word: 'kasırga', difficulty: 3 },
      { word: 'tsunami', difficulty: 3 },
      { word: 'göktaşı', difficulty: 3 },
      { word: 'buzul', difficulty: 3 },
      { word: 'mercan', difficulty: 3 },
      { word: 'fosil', difficulty: 3 },
      { word: 'stalaktit', difficulty: 3 },
    ],
  },
  teknoloji: {
    name: 'Teknoloji',
    emoji: '💻',
    words: [
      { word: 'robot', difficulty: 1 },
      { word: 'roket', difficulty: 1 },
      { word: 'uçak', difficulty: 1 },
      { word: 'araba', difficulty: 1 },
      { word: 'tren', difficulty: 1 },
      { word: 'gemi', difficulty: 1 },
      { word: 'kamera', difficulty: 1 },
      { word: 'tablet', difficulty: 1 },
      { word: 'klavye', difficulty: 1 },
      { word: 'fare', difficulty: 1 },
      { word: 'pil', difficulty: 1 },
      { word: 'helikopter', difficulty: 2 },
      { word: 'denizaltı', difficulty: 2 },
      { word: 'uydu', difficulty: 2 },
      { word: 'teleskop', difficulty: 2 },
      { word: 'mikroskop', difficulty: 2 },
      { word: 'drone', difficulty: 2 },
      { word: 'yazıcı', difficulty: 2 },
      { word: 'hoparlör', difficulty: 2 },
      { word: 'mikrofon', difficulty: 2 },
      { word: 'wifi', difficulty: 2 },
      { word: 'şarj aleti', difficulty: 2 },
      { word: 'flash bellek', difficulty: 2 },
      { word: 'lazer', difficulty: 2 },
      { word: 'radar', difficulty: 2 },
      { word: 'GPS', difficulty: 2 },
      { word: 'ekran', difficulty: 1 },
      { word: 'hard disk', difficulty: 2 },
      { word: 'anakart', difficulty: 3 },
      { word: 'işlemci', difficulty: 3 },
      { word: 'modem', difficulty: 2 },
      { word: 'projeksiyon', difficulty: 2 },
      { word: 'akıllı saat', difficulty: 2 },
      { word: 'güneş paneli', difficulty: 2 },
      { word: 'rüzgâr türbini', difficulty: 3 },
      { word: 'elektrik motoru', difficulty: 2 },
      { word: 'sensör', difficulty: 2 },
      { word: 'çip', difficulty: 2 },
      { word: 'barkod', difficulty: 2 },
      { word: 'QR kod', difficulty: 2 },
      { word: 'bluetooth', difficulty: 3 },
      { word: 'sanal gerçeklik', difficulty: 3 },
      { word: 'yapay zekâ', difficulty: 3 },
      { word: 'hologram', difficulty: 3 },
      { word: '3D yazıcı', difficulty: 3 },
      { word: 'nükleer santral', difficulty: 3 },
      { word: 'fiber optik', difficulty: 3 },
      { word: 'parmak izi okuyucu', difficulty: 3 },
      { word: 'elektrikli araba', difficulty: 2 },
      { word: 'otonom araç', difficulty: 3 },
      { word: 'navigasyon', difficulty: 2 },
      { word: 'uzaktan kumanda', difficulty: 2 },
      { word: 'adaptör', difficulty: 2 },
      { word: 'transformer', difficulty: 3 },
      { word: 'jeneratör', difficulty: 2 },
      { word: 'web kamerası', difficulty: 2 },
      { word: 'joystick', difficulty: 2 },
      { word: 'oyun konsolu', difficulty: 2 },
      { word: 'kulaklık', difficulty: 1 },
      { word: 'akıllı telefon', difficulty: 1 },
    ],
  },
  karisik: {
    name: 'Karışık',
    emoji: '🎲',
    words: [
      { word: 'okul', difficulty: 1 },
      { word: 'hastane', difficulty: 1 },
      { word: 'cami', difficulty: 1 },
      { word: 'köprü', difficulty: 1 },
      { word: 'kale', difficulty: 1 },
      { word: 'bayrak', difficulty: 1 },
      { word: 'harita', difficulty: 1 },
      { word: 'kılıç', difficulty: 1 },
      { word: 'bomba', difficulty: 1 },
      { word: 'ip', difficulty: 1 },
      { word: 'merdiven', difficulty: 1 },
      { word: 'salıncak', difficulty: 1 },
      { word: 'kaydırak', difficulty: 1 },
      { word: 'piramit', difficulty: 2 },
      { word: 'takvim', difficulty: 2 },
      { word: 'pusula', difficulty: 2 },
      { word: 'dürbün', difficulty: 2 },
      { word: 'palyaço', difficulty: 2 },
      { word: 'sihirbaz', difficulty: 2 },
      { word: 'korsan', difficulty: 2 },
      { word: 'ninja', difficulty: 2 },
      { word: 'süper kahraman', difficulty: 2 },
      { word: 'uzaylı', difficulty: 2 },
      { word: 'hayalet', difficulty: 2 },
      { word: 'vampir', difficulty: 2 },
      { word: 'zombi', difficulty: 2 },
      { word: 'ejderha', difficulty: 2 },
      { word: 'denizkızı', difficulty: 2 },
      { word: 'hazine sandığı', difficulty: 2 },
      { word: 'taht', difficulty: 2 },
      { word: 'kalkan', difficulty: 2 },
      { word: 'ok ve yay', difficulty: 2 },
      { word: 'dinamit', difficulty: 2 },
      { word: 'meşale', difficulty: 2 },
      { word: 'el feneri', difficulty: 2 },
      { word: 'çit', difficulty: 2 },
      { word: 'kuyu', difficulty: 2 },
      { word: 'lunapark', difficulty: 2 },
      { word: 'sirk', difficulty: 2 },
      { word: 'tek boynuzlu at', difficulty: 3 },
      { word: 'dönme dolap', difficulty: 2 },
      { word: 'atlıkarınca', difficulty: 2 },
      { word: 'havai fişek', difficulty: 2 },
      { word: 'balon', difficulty: 1 },
      { word: 'uçurtma', difficulty: 1 },
      { word: 'tahta', difficulty: 1 },
      { word: 'zar', difficulty: 1 },
      { word: 'satranç', difficulty: 2 },
      { word: 'bulmaca', difficulty: 2 },
      { word: 'bilmece', difficulty: 3 },
      { word: 'sihirli değnek', difficulty: 2 },
      { word: 'kristal küre', difficulty: 3 },
      { word: 'altın', difficulty: 1 },
      { word: 'elmas', difficulty: 2 },
      { word: 'hazine haritası', difficulty: 3 },
      { word: 'yelkenli', difficulty: 2 },
      { word: 'deniz feneri', difficulty: 2 },
      { word: 'gizli geçit', difficulty: 3 },
      { word: 'tuzak', difficulty: 2 },
      { word: 'çapa', difficulty: 2 },
      { word: 'düdük', difficulty: 2 },
      { word: 'megafon', difficulty: 2 },
    ],
  },

  // ===== NEW CATEGORIES =====

  ulasim: {
    name: 'Ulaşım',
    emoji: '🚗',
    words: [
      { word: 'araba', difficulty: 1 },
      { word: 'otobüs', difficulty: 1 },
      { word: 'taksi', difficulty: 1 },
      { word: 'bisiklet', difficulty: 1 },
      { word: 'tren', difficulty: 1 },
      { word: 'uçak', difficulty: 1 },
      { word: 'gemi', difficulty: 1 },
      { word: 'tekne', difficulty: 1 },
      { word: 'motosiklet', difficulty: 1 },
      { word: 'kamyon', difficulty: 1 },
      { word: 'minibüs', difficulty: 1 },
      { word: 'tramvay', difficulty: 2 },
      { word: 'metro', difficulty: 1 },
      { word: 'feribot', difficulty: 2 },
      { word: 'ambulans', difficulty: 1 },
      { word: 'itfaiye aracı', difficulty: 2 },
      { word: 'helikopter', difficulty: 2 },
      { word: 'tır', difficulty: 1 },
      { word: 'forklift', difficulty: 2 },
      { word: 'traktör', difficulty: 1 },
      { word: 'scooter', difficulty: 2 },
      { word: 'paten', difficulty: 1 },
      { word: 'kaykay', difficulty: 2 },
      { word: 'gondol', difficulty: 2 },
      { word: 'teleferik', difficulty: 2 },
      { word: 'yelkenli', difficulty: 2 },
      { word: 'kayık', difficulty: 1 },
      { word: 'sandal', difficulty: 2 },
      { word: 'kano', difficulty: 2 },
      { word: 'jet ski', difficulty: 2 },
      { word: 'balonla uçma', difficulty: 3 },
      { word: 'at arabası', difficulty: 2 },
      { word: 'fayton', difficulty: 2 },
      { word: 'tanker', difficulty: 2 },
      { word: 'vinç', difficulty: 2 },
      { word: 'buldozer', difficulty: 2 },
      { word: 'kepçe', difficulty: 2 },
      { word: 'itfaiye merdiveni', difficulty: 3 },
      { word: 'çekici', difficulty: 2 },
      { word: 'denizaltı', difficulty: 2 },
      { word: 'roket', difficulty: 1 },
      { word: 'uzay mekiği', difficulty: 3 },
      { word: 'planör', difficulty: 3 },
      { word: 'zeplin', difficulty: 3 },
      { word: 'mikrolight', difficulty: 3 },
      { word: 'dolmuş', difficulty: 1 },
      { word: 'vapur', difficulty: 2 },
      { word: 'yat', difficulty: 2 },
      { word: 'kruvaziyer', difficulty: 3 },
      { word: 'kar küreme aracı', difficulty: 3 },
      { word: 'ATV', difficulty: 2 },
      { word: 'lori', difficulty: 2 },
      { word: 'segway', difficulty: 3 },
      { word: 'kızak', difficulty: 1 },
      { word: 'kayak teleferik', difficulty: 2 },
    ],
  },
  muzik: {
    name: 'Müzik',
    emoji: '🎵',
    words: [
      { word: 'gitar', difficulty: 1 },
      { word: 'piyano', difficulty: 1 },
      { word: 'davul', difficulty: 1 },
      { word: 'keman', difficulty: 1 },
      { word: 'flüt', difficulty: 1 },
      { word: 'saz', difficulty: 1 },
      { word: 'ud', difficulty: 2 },
      { word: 'ney', difficulty: 2 },
      { word: 'akordeon', difficulty: 2 },
      { word: 'trompet', difficulty: 2 },
      { word: 'klarnet', difficulty: 2 },
      { word: 'org', difficulty: 2 },
      { word: 'bateri', difficulty: 1 },
      { word: 'tambur', difficulty: 2 },
      { word: 'def', difficulty: 2 },
      { word: 'zurna', difficulty: 2 },
      { word: 'nota', difficulty: 1 },
      { word: 'mikrofon', difficulty: 1 },
      { word: 'hoparlör', difficulty: 1 },
      { word: 'kulaklık', difficulty: 1 },
      { word: 'kaset', difficulty: 2 },
      { word: 'plak', difficulty: 2 },
      { word: 'pikap', difficulty: 2 },
      { word: 'sahne', difficulty: 1 },
      { word: 'konser', difficulty: 1 },
      { word: 'tef', difficulty: 1 },
      { word: 'darbuka', difficulty: 2 },
      { word: 'arp', difficulty: 2 },
      { word: 'çello', difficulty: 2 },
      { word: 'kontrbas', difficulty: 3 },
      { word: 'saksafon', difficulty: 2 },
      { word: 'trombon', difficulty: 3 },
      { word: 'obua', difficulty: 3 },
      { word: 'fagot', difficulty: 3 },
      { word: 'kanun', difficulty: 2 },
      { word: 'kemençe', difficulty: 3 },
      { word: 'bağlama', difficulty: 2 },
      { word: 'bendir', difficulty: 3 },
      { word: 'zil', difficulty: 1 },
      { word: 'kastanyet', difficulty: 3 },
      { word: 'marakas', difficulty: 2 },
      { word: 'ksilofon', difficulty: 3 },
      { word: 'metalofon', difficulty: 3 },
      { word: 'melodika', difficulty: 2 },
      { word: 'ukulele', difficulty: 2 },
      { word: 'banjo', difficulty: 2 },
      { word: 'mandolin', difficulty: 3 },
      { word: 'bas gitar', difficulty: 2 },
      { word: 'elektro gitar', difficulty: 2 },
      { word: 'mızıka', difficulty: 2 },
      { word: 'metronom', difficulty: 3 },
      { word: 'amfi', difficulty: 2 },
      { word: 'mikser', difficulty: 2 },
      { word: 'DJ masası', difficulty: 2 },
      { word: 'şarkı sözü', difficulty: 2 },
    ],
  },
  giysiler: {
    name: 'Giysi & Aksesuar',
    emoji: '👕',
    words: [
      { word: 'tişört', difficulty: 1 },
      { word: 'pantolon', difficulty: 1 },
      { word: 'etek', difficulty: 1 },
      { word: 'elbise', difficulty: 1 },
      { word: 'ceket', difficulty: 1 },
      { word: 'gömlek', difficulty: 1 },
      { word: 'kazak', difficulty: 1 },
      { word: 'şort', difficulty: 1 },
      { word: 'çorap', difficulty: 1 },
      { word: 'ayakkabı', difficulty: 1 },
      { word: 'bot', difficulty: 1 },
      { word: 'terlik', difficulty: 1 },
      { word: 'palto', difficulty: 1 },
      { word: 'mont', difficulty: 1 },
      { word: 'yelek', difficulty: 1 },
      { word: 'eşarp', difficulty: 2 },
      { word: 'kravat', difficulty: 1 },
      { word: 'papyon', difficulty: 2 },
      { word: 'kemer', difficulty: 1 },
      { word: 'eldiven', difficulty: 1 },
      { word: 'bere', difficulty: 1 },
      { word: 'fötr şapka', difficulty: 3 },
      { word: 'güneş gözlüğü', difficulty: 1 },
      { word: 'kolye', difficulty: 1 },
      { word: 'bilezik', difficulty: 1 },
      { word: 'yüzük', difficulty: 1 },
      { word: 'küpe', difficulty: 1 },
      { word: 'broş', difficulty: 2 },
      { word: 'saat', difficulty: 1 },
      { word: 'atkı', difficulty: 1 },
      { word: 'hırka', difficulty: 1 },
      { word: 'sweatshirt', difficulty: 2 },
      { word: 'kot pantolon', difficulty: 1 },
      { word: 'tayt', difficulty: 2 },
      { word: 'pijama', difficulty: 1 },
      { word: 'bornoz', difficulty: 2 },
      { word: 'mayo', difficulty: 1 },
      { word: 'bikini', difficulty: 2 },
      { word: 'trençkot', difficulty: 3 },
      { word: 'smokin', difficulty: 3 },
      { word: 'korsaj', difficulty: 3 },
      { word: 'taç', difficulty: 1 },
      { word: 'türban', difficulty: 2 },
      { word: 'başörtüsü', difficulty: 2 },
      { word: 'çizme', difficulty: 1 },
      { word: 'spor ayakkabı', difficulty: 1 },
      { word: 'topuklu ayakkabı', difficulty: 2 },
      { word: 'sandalet', difficulty: 1 },
      { word: 'önlük', difficulty: 1 },
      { word: 'şal', difficulty: 2 },
      { word: 'toka', difficulty: 1 },
      { word: 'saç bandı', difficulty: 2 },
      { word: 'kol düğmesi', difficulty: 3 },
      { word: 'kol saati', difficulty: 1 },
      { word: 'pelerin', difficulty: 2 },
      { word: 'iç çamaşırı', difficulty: 2 },
    ],
  },
  mekanlar: {
    name: 'Mekanlar & Yapılar',
    emoji: '🏠',
    words: [
      { word: 'ev', difficulty: 1 },
      { word: 'apartman', difficulty: 1 },
      { word: 'okul', difficulty: 1 },
      { word: 'hastane', difficulty: 1 },
      { word: 'cami', difficulty: 1 },
      { word: 'kilise', difficulty: 1 },
      { word: 'market', difficulty: 1 },
      { word: 'park', difficulty: 1 },
      { word: 'bahçe', difficulty: 1 },
      { word: 'köprü', difficulty: 1 },
      { word: 'kale', difficulty: 1 },
      { word: 'gökdelen', difficulty: 2 },
      { word: 'villa', difficulty: 2 },
      { word: 'kulübe', difficulty: 2 },
      { word: 'çadır', difficulty: 1 },
      { word: 'kule', difficulty: 1 },
      { word: 'fener', difficulty: 2 },
      { word: 'tünel', difficulty: 2 },
      { word: 'baraj', difficulty: 2 },
      { word: 'stadyum', difficulty: 2 },
      { word: 'havalimanı', difficulty: 2 },
      { word: 'liman', difficulty: 2 },
      { word: 'istasyon', difficulty: 2 },
      { word: 'fabrika', difficulty: 2 },
      { word: 'değirmen', difficulty: 2 },
      { word: 'ambar', difficulty: 2 },
      { word: 'ahır', difficulty: 2 },
      { word: 'sera', difficulty: 2 },
      { word: 'deniz feneri', difficulty: 2 },
      { word: 'restoran', difficulty: 1 },
      { word: 'kafe', difficulty: 1 },
      { word: 'sinema', difficulty: 1 },
      { word: 'tiyatro', difficulty: 2 },
      { word: 'müze', difficulty: 1 },
      { word: 'kütüphane', difficulty: 1 },
      { word: 'eczane', difficulty: 1 },
      { word: 'banka', difficulty: 1 },
      { word: 'postane', difficulty: 1 },
      { word: 'karakol', difficulty: 2 },
      { word: 'mahkeme', difficulty: 2 },
      { word: 'hapishane', difficulty: 2 },
      { word: 'saray', difficulty: 2 },
      { word: 'tapınak', difficulty: 2 },
      { word: 'manastır', difficulty: 3 },
      { word: 'kubbe', difficulty: 2 },
      { word: 'minare', difficulty: 2 },
      { word: 'çan kulesi', difficulty: 3 },
      { word: 'garaj', difficulty: 1 },
      { word: 'otopark', difficulty: 1 },
      { word: 'benzin istasyonu', difficulty: 2 },
      { word: 'AVM', difficulty: 1 },
      { word: 'pazar', difficulty: 1 },
      { word: 'hamam', difficulty: 2 },
      { word: 'kervansaray', difficulty: 3 },
      { word: 'han', difficulty: 2 },
      { word: 'çeşme', difficulty: 2 },
      { word: 'su kemeri', difficulty: 3 },
      { word: 'amfitiyatro', difficulty: 3 },
      { word: 'kışla', difficulty: 3 },
    ],
  },
  sanat: {
    name: 'Sanat & Eğlence',
    emoji: '🎭',
    words: [
      { word: 'tiyatro', difficulty: 1 },
      { word: 'sinema', difficulty: 1 },
      { word: 'konser', difficulty: 1 },
      { word: 'dans', difficulty: 1 },
      { word: 'resim', difficulty: 1 },
      { word: 'heykel', difficulty: 2 },
      { word: 'fotoğraf', difficulty: 1 },
      { word: 'opera', difficulty: 2 },
      { word: 'bale', difficulty: 2 },
      { word: 'seramik', difficulty: 2 },
      { word: 'origami', difficulty: 2 },
      { word: 'kukla', difficulty: 1 },
      { word: 'maske', difficulty: 1 },
      { word: 'perde', difficulty: 2 },
      { word: 'sahne', difficulty: 1 },
      { word: 'grafiti', difficulty: 2 },
      { word: 'mozaik', difficulty: 2 },
      { word: 'vitray', difficulty: 3 },
      { word: 'kaligrafi', difficulty: 3 },
      { word: 'ebru', difficulty: 2 },
      { word: 'minyatür', difficulty: 3 },
      { word: 'karikatür', difficulty: 2 },
      { word: 'çizgi roman', difficulty: 2 },
      { word: 'manga', difficulty: 2 },
      { word: 'anime', difficulty: 2 },
      { word: 'portre', difficulty: 2 },
      { word: 'tuval', difficulty: 2 },
      { word: 'fırça', difficulty: 1 },
      { word: 'boya', difficulty: 1 },
      { word: 'palet', difficulty: 2 },
      { word: 'karakalem', difficulty: 2 },
      { word: 'suluboya', difficulty: 2 },
      { word: 'yağlıboya', difficulty: 2 },
      { word: 'pastel', difficulty: 2 },
      { word: 'kolaj', difficulty: 3 },
      { word: 'soyut', difficulty: 3 },
      { word: 'gölge oyunu', difficulty: 3 },
      { word: 'karagöz', difficulty: 2 },
      { word: 'hacivat', difficulty: 2 },
      { word: 'skeç', difficulty: 2 },
      { word: 'stand-up', difficulty: 2 },
      { word: 'pantomim', difficulty: 3 },
      { word: 'sirk', difficulty: 1 },
      { word: 'akrobat', difficulty: 2 },
      { word: 'jonglör', difficulty: 3 },
      { word: 'illüzyon', difficulty: 3 },
      { word: 'stüdyo', difficulty: 2 },
      { word: 'galeri', difficulty: 2 },
      { word: 'sergi', difficulty: 2 },
      { word: 'ödül', difficulty: 2 },
      { word: 'festival', difficulty: 2 },
      { word: 'gişe', difficulty: 2 },
      { word: 'bilet', difficulty: 1 },
    ],
  },
  yemek_mutfak: {
    name: 'Mutfak & Pişirme',
    emoji: '🍳',
    words: [
      { word: 'fırın', difficulty: 1 },
      { word: 'ocak', difficulty: 1 },
      { word: 'tava', difficulty: 1 },
      { word: 'tencere', difficulty: 1 },
      { word: 'tabak', difficulty: 1 },
      { word: 'bardak', difficulty: 1 },
      { word: 'çatal', difficulty: 1 },
      { word: 'kaşık', difficulty: 1 },
      { word: 'bıçak', difficulty: 1 },
      { word: 'süzgeç', difficulty: 2 },
      { word: 'kevgir', difficulty: 2 },
      { word: 'merdane', difficulty: 2 },
      { word: 'hamur', difficulty: 1 },
      { word: 'maya', difficulty: 2 },
      { word: 'un', difficulty: 1 },
      { word: 'şeker', difficulty: 1 },
      { word: 'tuz', difficulty: 1 },
      { word: 'baharat', difficulty: 2 },
      { word: 'tarçın', difficulty: 2 },
      { word: 'zencefil', difficulty: 2 },
      { word: 'safran', difficulty: 3 },
      { word: 'vanilya', difficulty: 2 },
      { word: 'sirke', difficulty: 2 },
      { word: 'sos', difficulty: 1 },
      { word: 'krema', difficulty: 2 },
      { word: 'tereyağı', difficulty: 1 },
      { word: 'zeytinyağı', difficulty: 2 },
      { word: 'sıvı yağ', difficulty: 1 },
      { word: 'buzdolabı', difficulty: 1 },
      { word: 'mikser', difficulty: 2 },
      { word: 'blender', difficulty: 2 },
      { word: 'rondo', difficulty: 2 },
      { word: 'tost makinesi', difficulty: 2 },
      { word: 'ekmek kızartma', difficulty: 2 },
      { word: 'çaydanlık', difficulty: 1 },
      { word: 'cezve', difficulty: 2 },
      { word: 'demlik', difficulty: 2 },
      { word: 'kahve makinesi', difficulty: 2 },
      { word: 'mangal', difficulty: 1 },
      { word: 'ızgara', difficulty: 1 },
      { word: 'şiş', difficulty: 2 },
      { word: 'tahta kaşık', difficulty: 2 },
      { word: 'rende', difficulty: 2 },
      { word: 'doğrama tahtası', difficulty: 2 },
      { word: 'tartı', difficulty: 2 },
      { word: 'ölçü kabı', difficulty: 2 },
      { word: 'çırpıcı', difficulty: 2 },
      { word: 'kalıp', difficulty: 2 },
      { word: 'tepsi', difficulty: 1 },
      { word: 'güveç', difficulty: 2 },
      { word: 'düdüklü tencere', difficulty: 3 },
      { word: 'fritöz', difficulty: 2 },
      { word: 'bulaşık makinesi', difficulty: 2 },
      { word: 'sünger', difficulty: 1 },
      { word: 'deterjan', difficulty: 2 },
      { word: 'peçete', difficulty: 1 },
      { word: 'önlük', difficulty: 1 },
      { word: 'havan', difficulty: 2 },
      { word: 'kavanoz', difficulty: 1 },
      { word: 'konserve açacağı', difficulty: 2 },
    ],
  },
  tarih: {
    name: 'Tarih & Kültür',
    emoji: '🏛️',
    words: [
      { word: 'piramit', difficulty: 1 },
      { word: 'kılıç', difficulty: 1 },
      { word: 'kalkan', difficulty: 1 },
      { word: 'ok', difficulty: 1 },
      { word: 'yay', difficulty: 1 },
      { word: 'bayrak', difficulty: 1 },
      { word: 'harita', difficulty: 1 },
      { word: 'taht', difficulty: 1 },
      { word: 'taç', difficulty: 1 },
      { word: 'zırh', difficulty: 2 },
      { word: 'mızrak', difficulty: 2 },
      { word: 'top', difficulty: 1 },
      { word: 'gemi', difficulty: 1 },
      { word: 'ferman', difficulty: 2 },
      { word: 'mühür', difficulty: 2 },
      { word: 'pusula', difficulty: 2 },
      { word: 'saat kulesi', difficulty: 2 },
      { word: 'anıt', difficulty: 2 },
      { word: 'heykel', difficulty: 2 },
      { word: 'lahit', difficulty: 3 },
      { word: 'papirüs', difficulty: 3 },
      { word: 'mumya', difficulty: 2 },
      { word: 'sfenks', difficulty: 3 },
      { word: 'kale', difficulty: 1 },
      { word: 'sur', difficulty: 2 },
      { word: 'hendek', difficulty: 2 },
      { word: 'köprü', difficulty: 1 },
      { word: 'tuğra', difficulty: 3 },
      { word: 'padişah', difficulty: 2 },
      { word: 'sultan', difficulty: 2 },
      { word: 'şövalye', difficulty: 2 },
      { word: 'gladyatör', difficulty: 2 },
      { word: 'samuray', difficulty: 2 },
      { word: 'viking', difficulty: 2 },
      { word: 'atlas', difficulty: 2 },
      { word: 'küre', difficulty: 2 },
      { word: 'tekerlek', difficulty: 1 },
      { word: 'matbaa', difficulty: 3 },
      { word: 'parşömen', difficulty: 3 },
      { word: 'el yazması', difficulty: 3 },
      { word: 'sikke', difficulty: 2 },
      { word: 'para', difficulty: 1 },
      { word: 'terazi', difficulty: 2 },
      { word: 'güneş saati', difficulty: 3 },
      { word: 'kum saati', difficulty: 2 },
      { word: 'mancınık', difficulty: 3 },
      { word: 'kuşatma kulesi', difficulty: 3 },
      { word: 'savaş arabası', difficulty: 3 },
      { word: 'hilal', difficulty: 2 },
      { word: 'çini', difficulty: 2 },
      { word: 'kilim', difficulty: 1 },
      { word: 'halı', difficulty: 1 },
      { word: 'sedef', difficulty: 3 },
      { word: 'osmanlı tuğrası', difficulty: 3 },
    ],
  },
  duygular: {
    name: 'Duygular & Kavramlar',
    emoji: '💭',
    words: [
      { word: 'mutluluk', difficulty: 2 },
      { word: 'üzüntü', difficulty: 2 },
      { word: 'korku', difficulty: 2 },
      { word: 'öfke', difficulty: 2 },
      { word: 'şaşkınlık', difficulty: 2 },
      { word: 'aşk', difficulty: 2 },
      { word: 'barış', difficulty: 2 },
      { word: 'savaş', difficulty: 2 },
      { word: 'özgürlük', difficulty: 3 },
      { word: 'hayal', difficulty: 3 },
      { word: 'rüya', difficulty: 2 },
      { word: 'kabus', difficulty: 2 },
      { word: 'nostalji', difficulty: 3 },
      { word: 'merak', difficulty: 3 },
      { word: 'cesaret', difficulty: 3 },
      { word: 'umut', difficulty: 3 },
      { word: 'sabır', difficulty: 3 },
      { word: 'kıskançlık', difficulty: 3 },
      { word: 'gurur', difficulty: 3 },
      { word: 'utanç', difficulty: 3 },
      { word: 'heyecan', difficulty: 2 },
      { word: 'sıkıntı', difficulty: 2 },
      { word: 'yalnızlık', difficulty: 3 },
      { word: 'dostluk', difficulty: 2 },
      { word: 'sevgi', difficulty: 2 },
      { word: 'nefret', difficulty: 3 },
      { word: 'güven', difficulty: 3 },
      { word: 'ihanet', difficulty: 3 },
      { word: 'özlem', difficulty: 3 },
      { word: 'ağlamak', difficulty: 1 },
      { word: 'gülmek', difficulty: 1 },
      { word: 'bağırmak', difficulty: 2 },
      { word: 'fısıldamak', difficulty: 3 },
      { word: 'sarılmak', difficulty: 1 },
      { word: 'el sıkışmak', difficulty: 2 },
      { word: 'öpücük', difficulty: 1 },
      { word: 'gözyaşı', difficulty: 2 },
      { word: 'gülümseme', difficulty: 1 },
      { word: 'kaş çatmak', difficulty: 3 },
      { word: 'sevinç', difficulty: 2 },
      { word: 'acı', difficulty: 2 },
      { word: 'huzur', difficulty: 3 },
      { word: 'stres', difficulty: 2 },
      { word: 'panik', difficulty: 2 },
      { word: 'şok', difficulty: 2 },
      { word: 'meditasyon', difficulty: 3 },
      { word: 'ilham', difficulty: 3 },
      { word: 'hayal kırıklığı', difficulty: 3 },
      { word: 'pişmanlık', difficulty: 3 },
      { word: 'minnettarlık', difficulty: 3 },
      { word: 'empati', difficulty: 3 },
      { word: 'öz güven', difficulty: 3 },
    ],
  },
  tatil: {
    name: 'Tatil & Seyahat',
    emoji: '✈️',
    words: [
      { word: 'bavul', difficulty: 1 },
      { word: 'pasaport', difficulty: 1 },
      { word: 'bilet', difficulty: 1 },
      { word: 'otel', difficulty: 1 },
      { word: 'havuz', difficulty: 1 },
      { word: 'plaj', difficulty: 1 },
      { word: 'kumsal', difficulty: 1 },
      { word: 'deniz', difficulty: 1 },
      { word: 'mayo', difficulty: 1 },
      { word: 'güneş kremi', difficulty: 2 },
      { word: 'şezlong', difficulty: 2 },
      { word: 'palet', difficulty: 2 },
      { word: 'şnorkel', difficulty: 2 },
      { word: 'fotoğraf makinesi', difficulty: 2 },
      { word: 'hatıra', difficulty: 2 },
      { word: 'kartpostal', difficulty: 2 },
      { word: 'tur otobüsü', difficulty: 2 },
      { word: 'gezi rehberi', difficulty: 2 },
      { word: 'çadır', difficulty: 1 },
      { word: 'kamp ateşi', difficulty: 2 },
      { word: 'uyku tulumu', difficulty: 2 },
      { word: 'sırt çantası', difficulty: 1 },
      { word: 'harita', difficulty: 1 },
      { word: 'pusula', difficulty: 2 },
      { word: 'dürbün', difficulty: 2 },
      { word: 'güneş şemsiyesi', difficulty: 2 },
      { word: 'dalgıç gözlüğü', difficulty: 2 },
      { word: 'can yeleği', difficulty: 2 },
      { word: 'el feneri', difficulty: 1 },
      { word: 'termos', difficulty: 2 },
      { word: 'piknik', difficulty: 1 },
      { word: 'barbekü', difficulty: 2 },
      { word: 'hamak', difficulty: 2 },
      { word: 'güneş gözlüğü', difficulty: 1 },
      { word: 'şapka', difficulty: 1 },
      { word: 'sandalet', difficulty: 1 },
      { word: 'sörf tahtası', difficulty: 2 },
      { word: 'kano', difficulty: 2 },
      { word: 'balık tutmak', difficulty: 2 },
      { word: 'yüzme havuzu', difficulty: 1 },
      { word: 'su kaydırağı', difficulty: 2 },
      { word: 'dalga', difficulty: 1 },
      { word: 'kum kalesi', difficulty: 1 },
      { word: 'deniz kabuğu', difficulty: 2 },
      { word: 'denizyıldızı', difficulty: 2 },
      { word: 'palmiye', difficulty: 2 },
      { word: 'hindistan cevizi', difficulty: 3 },
      { word: 'gün batımı', difficulty: 1 },
      { word: 'uçak bileti', difficulty: 2 },
      { word: 'check-in', difficulty: 3 },
      { word: 'vize', difficulty: 2 },
      { word: 'döviz', difficulty: 2 },
      { word: 'hediyelik eşya', difficulty: 2 },
      { word: 'müze', difficulty: 1 },
      { word: 'tarihi yer', difficulty: 2 },
    ],
  },
  bilim: {
    name: 'Bilim & Uzay',
    emoji: '🔬',
    words: [
      { word: 'atom', difficulty: 2 },
      { word: 'molekül', difficulty: 2 },
      { word: 'DNA', difficulty: 2 },
      { word: 'hücre', difficulty: 2 },
      { word: 'bakteri', difficulty: 2 },
      { word: 'virüs', difficulty: 2 },
      { word: 'deney tüpü', difficulty: 2 },
      { word: 'mikroskop', difficulty: 2 },
      { word: 'teleskop', difficulty: 2 },
      { word: 'gezegen', difficulty: 1 },
      { word: 'yıldız', difficulty: 1 },
      { word: 'galaksi', difficulty: 2 },
      { word: 'kara delik', difficulty: 3 },
      { word: 'asteroid', difficulty: 3 },
      { word: 'kuyruklu yıldız', difficulty: 3 },
      { word: 'uzay istasyonu', difficulty: 3 },
      { word: 'uydu', difficulty: 2 },
      { word: 'ay tutulması', difficulty: 3 },
      { word: 'güneş tutulması', difficulty: 3 },
      { word: 'fosil', difficulty: 2 },
      { word: 'dinozor', difficulty: 1 },
      { word: 'iskelet', difficulty: 1 },
      { word: 'beyin', difficulty: 2 },
      { word: 'kalp', difficulty: 1 },
      { word: 'akciğer', difficulty: 2 },
      { word: 'göz', difficulty: 1 },
      { word: 'kan', difficulty: 1 },
      { word: 'sinir sistemi', difficulty: 3 },
      { word: 'roket', difficulty: 1 },
      { word: 'astronot', difficulty: 2 },
      { word: 'uzay giysisi', difficulty: 2 },
      { word: 'güneş sistemi', difficulty: 2 },
      { word: 'dünya', difficulty: 1 },
      { word: 'mars', difficulty: 1 },
      { word: 'ay', difficulty: 1 },
      { word: 'güneş', difficulty: 1 },
      { word: 'satürn', difficulty: 2 },
      { word: 'jüpiter', difficulty: 2 },
      { word: 'nebula', difficulty: 3 },
      { word: 'süpernova', difficulty: 3 },
      { word: 'laboratuvar', difficulty: 2 },
      { word: 'formül', difficulty: 2 },
      { word: 'deney', difficulty: 1 },
      { word: 'robot', difficulty: 1 },
      { word: 'yapay zekâ', difficulty: 3 },
      { word: 'lazer', difficulty: 2 },
      { word: 'mıknatıs', difficulty: 1 },
      { word: 'pil', difficulty: 1 },
      { word: 'elektrik', difficulty: 1 },
      { word: 'voltaj', difficulty: 2 },
      { word: 'termometre', difficulty: 2 },
      { word: 'barometre', difficulty: 3 },
      { word: 'periyodik tablo', difficulty: 3 },
      { word: 'kimyasal reaksiyon', difficulty: 3 },
      { word: 'evrim', difficulty: 3 },
      { word: 'yer çekimi', difficulty: 2 },
      { word: 'prizma', difficulty: 2 },
      { word: 'büyüteç', difficulty: 1 },
    ],
  },
};
